#!/bin/bash

prefix=$1
[[ -z $prefix ]] && echo "USAGE: ./install /path/prefix" && exit 65
[[ ! -d $prefix ]] && echo "error: directory '$prefix' not existing" && exit 65
cp -a README.md LICENSE share bin $prefix/
echo -e "Add PATH: $(readlink -f $prefix/bin)"
